// BLX - Shared blog post rendering logic for both index.html and blogs.html
// Uses staticBlogPosts from blog-data.js (generated by generate-static-blog-index.py)

document.addEventListener('DOMContentLoaded', function() {
    renderBlogPosts();
});

function renderBlogPosts() {
    const blogContainer = document.getElementById('blog-posts');
    if (!blogContainer) return;

    // BLX - Check for data-limit attribute (used on front page to show only recent posts)
    const limit = blogContainer.getAttribute('data-limit');
    let posts = (typeof staticBlogPosts !== 'undefined') ? [...staticBlogPosts] : [];

    // Sort by timestamp descending (newest first)
    posts.sort((a, b) => {
        const tsA = a.timestamp || 0;
        const tsB = b.timestamp || 0;
        return tsB - tsA;
    });

    // Apply limit if specified
    if (limit && !isNaN(limit)) {
        posts = posts.slice(0, parseInt(limit));
    }

    if (posts.length === 0) {
        blogContainer.innerHTML = '<p>No blog posts found.</p>';
        return;
    }

    blogContainer.innerHTML = '';

    posts.forEach(post => {
        const preview = createBlogPreview(post);
        blogContainer.appendChild(preview);
    });
}

function createBlogPreview(post) {
    const article = document.createElement('article');
    article.className = 'blog-preview';

    const title = document.createElement('h2');
    const titleLink = document.createElement('a');
    titleLink.href = `blog-posts/${post.filename}`;
    titleLink.textContent = post.title;
    title.appendChild(titleLink);

    const date = document.createElement('p');
    date.innerHTML = `<em>Posted: ${post.date}</em>`;

    const excerpt = document.createElement('p');
    excerpt.textContent = post.excerpt;

    const tags = document.createElement('div');
    tags.className = 'tags';
    if (post.tags && post.tags.length > 0) {
        post.tags.forEach(tag => {
            const tagSpan = document.createElement('span');
            tagSpan.className = 'tag';
            tagSpan.textContent = tag;
            tags.appendChild(tagSpan);
        });
    }

    const readMore = document.createElement('p');
    const readMoreLink = document.createElement('a');
    readMoreLink.href = `blog-posts/${post.filename}`;
    readMoreLink.textContent = 'Read more...';
    readMore.appendChild(readMoreLink);

    article.appendChild(title);
    article.appendChild(date);
    article.appendChild(excerpt);
    article.appendChild(tags);
    article.appendChild(readMore);

    return article;
}
