// BLX - Auto-generated GitHub activity data on 2026-08-10T07:39:48Z
// This file is generated by scripts/generate-github-data.py
// Do not edit manually - rendering logic is in github-activity.js

window.GITHUB_DATA = {
  "generated_at": "2026-08-10T07:39:48Z",
  "profile": {
    "login": "Blenux",
    "name": "Blenux",
    "avatar_url": "https://avatars.githubusercontent.com/u/25260650?v=4",
    "bio": "Married.\r\nDad of 3.\r\nLinux / Open Source FTW!\r\nSelf Taught.\r\nLearning to Code.\r\nInto many things, but master of none!",
    "public_repos": 26,
    "followers": 15,
    "html_url": "https://github.com/Blenux"
  },
  "owned_repos": [
    {
      "name": "Blenux.github.io",
      "full_name": "Blenux/Blenux.github.io",
      "html_url": "https://github.com/Blenux/Blenux.github.io",
      "description": null,
      "updated_at": "2026-08-10T01:44:21Z",
      "default_branch": "main"
    },
    {
      "name": "blender-extensions",
      "full_name": "Blenux/blender-extensions",
      "html_url": "https://github.com/Blenux/blender-extensions",
      "description": "My Blender Extensions.",
      "updated_at": "2026-08-09T01:11:41Z",
      "default_branch": "main"
    },
    {
      "name": "UEViewer",
      "full_name": "Blenux/UEViewer",
      "html_url": "https://github.com/Blenux/UEViewer",
      "description": "Viewer and exporter for Unreal Engine 1-4 assets (UE Viewer).",
      "updated_at": "2026-07-29T23:10:36Z",
      "default_branch": "master"
    },
    {
      "name": "BeamNG-Workspace",
      "full_name": "Blenux/BeamNG-Workspace",
      "html_url": "https://github.com/Blenux/BeamNG-Workspace",
      "description": "Just some scripts I made for BeamNG.drive",
      "updated_at": "2026-06-28T08:48:26Z",
      "default_branch": "main"
    },
    {
      "name": "Blender-JBeam-Editor",
      "full_name": "Blenux/Blender-JBeam-Editor",
      "html_url": "https://github.com/Blenux/Blender-JBeam-Editor",
      "description": "Blender plugin to import, modify, and export JBeam.",
      "updated_at": "2026-06-19T07:16:43Z",
      "default_branch": "main"
    },
    {
      "name": "blender-keep-collada",
      "full_name": "Blenux/blender-keep-collada",
      "html_url": "https://github.com/Blenux/blender-keep-collada",
      "description": "blender with collada added back",
      "updated_at": "2026-04-13T01:00:15Z",
      "default_branch": "keep-collada"
    }
  ],
  "owned_detail": [
    {
      "name": "Blenux.github.io",
      "repoUrl": "https://github.com/Blenux/Blenux.github.io",
      "branches": [
        {
          "branch": "main",
          "commits": [
            {
              "message": "Auto-generated blog posts and GitHub activity data [skip ci]",
              "url": "https://github.com/Blenux/Blenux.github.io/commit/aad8397f792f5887365973d68561054ff6b33031",
              "date": "2026-08-10T01:44:17Z"
            },
            {
              "message": "Auto-generated blog posts and GitHub activity data [skip ci]",
              "url": "https://github.com/Blenux/Blenux.github.io/commit/068bcc2808523553b37919cb22742c5ae4ad625c",
              "date": "2026-08-09T18:39:05Z"
            },
            {
              "message": "Auto-generated blog posts and GitHub activity data [skip ci]",
              "url": "https://github.com/Blenux/Blenux.github.io/commit/69d3775acac2ae529f97ac4087c04e1bb94ab0c1",
              "date": "2026-08-09T12:48:12Z"
            },
            {
              "message": "Auto-generated blog posts and GitHub activity data [skip ci]",
              "url": "https://github.com/Blenux/Blenux.github.io/commit/5d49622776716a40cc8322e2acdd87ec68c9062b",
              "date": "2026-08-09T06:55:10Z"
            },
            {
              "message": "Rewrite About page with more casual tone and reorganized content sections",
              "url": "https://github.com/Blenux/Blenux.github.io/commit/e5d53e0f80aa544b688543eb3eca14752668676b",
              "date": "2026-08-09T03:03:34Z"
            }
          ]
        }
      ]
    },
    {
      "name": "blender-extensions",
      "repoUrl": "https://github.com/Blenux/blender-extensions",
      "branches": [
        {
          "branch": "main",
          "commits": [
            {
              "message": "standardize font-size to 14px and replace padding values with var(--gap)",
              "url": "https://github.com/Blenux/blender-extensions/commit/28fc893eef9e2ec004919efa7a2e91dfe22e75ab",
              "date": "2026-08-09T01:11:36Z"
            },
            {
              "message": "clarify drag-and-drop behavior to add repository instead of direct installation",
              "url": "https://github.com/Blenux/blender-extensions/commit/d7589ffc462f01cc16031631543d764f6065515d",
              "date": "2026-08-09T01:08:04Z"
            },
            {
              "message": "reorder installation guide steps and update drag-and-drop to use extension zip instead of repository URL",
              "url": "https://github.com/Blenux/blender-extensions/commit/12d95414074a0d09bf8eca0507f00b4356f232aa",
              "date": "2026-08-09T01:05:29Z"
            },
            {
              "message": "uncomment and set font-size to 14px for table header and body cells",
              "url": "https://github.com/Blenux/blender-extensions/commit/e68bd4de8c970170dde2f9c711756152df726ecd",
              "date": "2026-08-09T01:00:46Z"
            },
            {
              "message": "comment out font-size declarations in table header and body cells",
              "url": "https://github.com/Blenux/blender-extensions/commit/003d6eb46ce4ff77a8abf24c49a937511127e828",
              "date": "2026-08-09T00:58:32Z"
            }
          ]
        }
      ]
    },
    {
      "name": "UEViewer",
      "repoUrl": "https://github.com/Blenux/UEViewer",
      "branches": [
        {
          "branch": "linux",
          "commits": [
            {
              "message": "Update Linux section to specify GUI context",
              "url": "https://github.com/Blenux/UEViewer/commit/7e5d4a2a6afcf82dca62f997f0f7a163b98f2056",
              "date": "2026-07-12T02:05:58Z"
            },
            {
              "message": "Linux branch",
              "url": "https://github.com/Blenux/UEViewer/commit/78f27fa82a7b3f76450cd2b3561fddce49607880",
              "date": "2026-07-12T02:03:29Z"
            },
            {
              "message": "Merged pull requests #317 and #318",
              "url": "https://github.com/Blenux/UEViewer/commit/a0bfb468d42be831b126632fd8a0ae6b3614f981",
              "date": "2024-02-23T08:53:57Z"
            },
            {
              "message": "-psk option didn't work\n\n#303",
              "url": "https://github.com/Blenux/UEViewer/commit/008f4dd554e0a03f7a43462a88bec822ec1aee7d",
              "date": "2023-07-07T12:14:14Z"
            },
            {
              "message": "Special FRotator class for UE4 (FRotator4)",
              "url": "https://github.com/Blenux/UEViewer/commit/d1e89f748e09316fcf5f01570ceda9aa75e46ec4",
              "date": "2022-10-23T09:44:58Z"
            }
          ]
        },
        {
          "branch": "master",
          "commits": [
            {
              "message": "Merged pull requests #317 and #318",
              "url": "https://github.com/Blenux/UEViewer/commit/a0bfb468d42be831b126632fd8a0ae6b3614f981",
              "date": "2024-02-23T08:53:57Z"
            },
            {
              "message": "-psk option didn't work\n\n#303",
              "url": "https://github.com/Blenux/UEViewer/commit/008f4dd554e0a03f7a43462a88bec822ec1aee7d",
              "date": "2023-07-07T12:14:14Z"
            },
            {
              "message": "Special FRotator class for UE4 (FRotator4)",
              "url": "https://github.com/Blenux/UEViewer/commit/d1e89f748e09316fcf5f01570ceda9aa75e46ec4",
              "date": "2022-10-23T09:44:58Z"
            },
            {
              "message": "Support for UE4 StaticMesh sockets\n\nJust loading and dumping, no visualization or export",
              "url": "https://github.com/Blenux/UEViewer/commit/1fa8fe293b4849f2143bd06c994b5a019b167e90",
              "date": "2022-10-21T22:16:41Z"
            },
            {
              "message": "Fixed work with huge files in UE4 pak files\n\nFPakEntry::StructSize is now 32 bit",
              "url": "https://github.com/Blenux/UEViewer/commit/c444911a6ad65bff5266f273dd5bdf7dd6fb506e",
              "date": "2022-04-16T08:08:01Z"
            }
          ]
        }
      ]
    },
    {
      "name": "BeamNG-Workspace",
      "repoUrl": "https://github.com/Blenux/BeamNG-Workspace",
      "branches": [
        {
          "branch": "main",
          "commits": [
            {
              "message": "Update README title and introduction\n\nChanged the title of the README and modified the introductory text.",
              "url": "https://github.com/Blenux/BeamNG-Workspace/commit/c5c944fc7832175b63b7c1cbadd75e38b3b7289e",
              "date": "2026-06-28T08:48:22Z"
            },
            {
              "message": "Revise README wording for usage and credit\n\nUpdated wording for clarity and formality in the README.",
              "url": "https://github.com/Blenux/BeamNG-Workspace/commit/853f990076d371ddad5ca15deb28d972954a6232",
              "date": "2026-06-28T08:47:59Z"
            },
            {
              "message": "Updated README\n\nUpdated README",
              "url": "https://github.com/Blenux/BeamNG-Workspace/commit/1544a96fa94fd1499d3723ccfbca448c022bb42a",
              "date": "2025-11-16T04:00:20Z"
            },
            {
              "message": "Initial commit",
              "url": "https://github.com/Blenux/BeamNG-Workspace/commit/d2b54df36f831aac9f18ddf8749bb281a7c62c0e",
              "date": "2025-09-21T12:03:36Z"
            }
          ]
        }
      ]
    }
  ],
  "contrib_repos": [
    {
      "name": "Bforartists",
      "full_name": "Bforartists/Bforartists",
      "html_url": "https://github.com/Bforartists/Bforartists",
      "description": "",
      "contrib": true
    }
  ],
  "contrib_detail": [
    {
      "name": "Bforartists",
      "repoUrl": "https://github.com/Bforartists/Bforartists",
      "branches": [
        {
          "branch": "main",
          "commits": [
            {
              "message": "6732-properties-editor---world---open-node-editor-button-to-open-shad… (#6735)\n\nWorld Properties - Add Open Shader Editor operator button\n\nAdds a new \"Open Shader Editor\" button to the World Properties panel that opens a Shader Editor window configured for the active world's node tree. Implements WORLD_OT_open_node_editor operator following the same pattern as the existing material and texture node editor operators.",
              "url": "https://github.com/Bforartists/Bforartists/commit/65829a5acabcc8a52a5b9175badc51bdfed39774",
              "date": "2026-08-07T23:06:42Z"
            },
            {
              "message": "6731-properties-editor---materials---open-node-editor-button-only-wor… (#6734)\n\n-- Cycles Material Panel - Add Open Shader Editor operator button",
              "url": "https://github.com/Bforartists/Bforartists/commit/f14571f41862e5c6d82e07dc6bb8eedaa730750c",
              "date": "2026-08-07T23:06:33Z"
            },
            {
              "message": "3D View - Header - Overlay toggles - Add \"Lock Object Mode\" button (#6657)\n\n-- added lock object to the Align View Buttons addon",
              "url": "https://github.com/Bforartists/Bforartists/commit/611151108de2ad918a842fbc79f753d36bbe8ada",
              "date": "2026-06-22T15:11:33Z"
            },
            {
              "message": "Sequencer - Color Strip - Add Width and Height to sidebar (#6647)\n\n-- Replaced the manual duplicated codebase of the strip classes (which can get outdated), and instead just directly import the Strip Properties contents.",
              "url": "https://github.com/Bforartists/Bforartists/commit/622107c6d2f5764bf76b4dc95a1e1c3d1e8e7018",
              "date": "2026-06-15T22:45:34Z"
            },
            {
              "message": "UI - Geometry Nodes - Nodegroups based modifiers layout adjustments (#6649)\n\n-- Fixed layout alignment issues, only affects the one listed below\n\nSOCK_MENU\nSOCK_OBJECT\nSOCK_IMAGE",
              "url": "https://github.com/Bforartists/Bforartists/commit/87891afc155540237b7b0d62b0ae15a8d9fd8509",
              "date": "2026-06-15T22:44:55Z"
            },
            {
              "message": "Node Editor - Remove double \"New Group\" oeprator (#6650)\n\n-- Removed the duplicated New Group, kept the top one.",
              "url": "https://github.com/Bforartists/Bforartists/commit/bbda79319286421c15f9802d4c85bc5fbbfb07b5",
              "date": "2026-06-15T22:44:12Z"
            },
            {
              "message": "Crash: Cycles on HIP-RT GPU mode (#6621)\n\n* Crash: Cycles on HIP-RT GPU mode - added a graceful fallback to not crash on no RT compatible GPUs from AMD if without the generation #6617\n\n* Fix HIPRT crash\n\n-- !is_light() was the cause (which blender commits says this was moved a year ago??)\n\nhttps://projects.blender.org/blender/blender/pulls/139798\n\n* remove the previous fix\n\n---------\n\nCo-authored-by: Andres Stephens <ondraise15@hotmail.com>",
              "url": "https://github.com/Bforartists/Bforartists/commit/97a50f8cb768a88f792d088b93756c3bab1dbb2b",
              "date": "2026-06-06T17:44:40Z"
            },
            {
              "message": "File Browser - Expose hotkey only selection and walk operators to the… (#6620)\n\n-- added up/down/left/right hotkeys to the File Browser - Select header menu",
              "url": "https://github.com/Bforartists/Bforartists/commit/da99d1f23cd14318ac4549cd83c9cf097d04dd52",
              "date": "2026-06-05T18:01:19Z"
            },
            {
              "message": "Outliner - Recent merge issues (#6619)\n\n-- Fixed up use_sync_select/scroll_to_active indent issue\n-- Removed the duplicated consolidated codebases of our OUTLINER_PT_options_search and OUTLINER_PT_options_filter changes and moved it back to their own classes (see below) with our DISCLOSURE arrows.\n\nThis was done since has other parts of GUI are now using this (like VIEW3D_PT_shading)",
              "url": "https://github.com/Bforartists/Bforartists/commit/7973de60951eb1e7856b8e99e090ee657c285dd6",
              "date": "2026-06-05T18:01:01Z"
            },
            {
              "message": "File Browser - Make a new operator to move to start or end of the fol… (#6612)\n\n-- Added Navigation to the File Browser header\n-- Added To Top/To Bottom Operators\n-- Added keymaps for To Top/To Bottom operators to all keymap presets.",
              "url": "https://github.com/Bforartists/Bforartists/commit/bd75398ff678dddee15c31142917a298f13ccb7a",
              "date": "2026-06-04T17:03:56Z"
            }
          ]
        }
      ]
    }
  ]
};
