// BLX - Auto-generated GitHub activity data on 2026-08-31T12:49:08Z
// This file is generated by scripts/generate-github-data.py
// Do not edit manually - rendering logic is in github-activity.js

window.GITHUB_DATA = {
  "generated_at": "2026-08-31T12:49:08Z",
  "profile": {
    "login": "Blenux",
    "name": "Blenux",
    "avatar_url": "https://avatars.githubusercontent.com/u/25260650?v=4",
    "bio": "Married.\r\nDad of 3.\r\nLinux / Open Source FTW!\r\nSelf Taught.\r\nLearning to Code.\r\nInto many things, but master of none!",
    "public_repos": 27,
    "followers": 15,
    "html_url": "https://github.com/Blenux"
  },
  "owned_repos": [
    {
      "name": "Blenux.github.io",
      "full_name": "Blenux/Blenux.github.io",
      "html_url": "https://github.com/Blenux/Blenux.github.io",
      "description": null,
      "updated_at": "2026-08-31T03:55:10Z",
      "default_branch": "main"
    },
    {
      "name": "Blender-JBeam-Editor",
      "full_name": "Blenux/Blender-JBeam-Editor",
      "html_url": "https://github.com/Blenux/Blender-JBeam-Editor",
      "description": "Blender plugin to import, modify, and export JBeam.",
      "updated_at": "2026-08-29T04:14:28Z",
      "default_branch": "main"
    },
    {
      "name": "scripts",
      "full_name": "Blenux/scripts",
      "html_url": "https://github.com/Blenux/scripts",
      "description": "Just a collection of scripts I've created for various things, all in one place.",
      "updated_at": "2026-08-19T10:55:57Z",
      "default_branch": "main"
    },
    {
      "name": "io_beamng_dae_dev",
      "full_name": "Blenux/io_beamng_dae_dev",
      "html_url": "https://github.com/Blenux/io_beamng_dae_dev",
      "description": "Source of my BeamNG Collada Importer/Exporter",
      "updated_at": "2026-08-16T05:52:17Z",
      "default_branch": "main"
    },
    {
      "name": "blender-extensions",
      "full_name": "Blenux/blender-extensions",
      "html_url": "https://github.com/Blenux/blender-extensions",
      "description": "My Blender Extensions.",
      "updated_at": "2026-08-16T05:35:09Z",
      "default_branch": "main"
    },
    {
      "name": "UEViewer",
      "full_name": "Blenux/UEViewer",
      "html_url": "https://github.com/Blenux/UEViewer",
      "description": "Viewer and exporter for Unreal Engine 1-4 assets (UE Viewer).",
      "updated_at": "2026-07-29T23:10:36Z",
      "default_branch": "master"
    }
  ],
  "owned_detail": [
    {
      "name": "Blenux.github.io",
      "repoUrl": "https://github.com/Blenux/Blenux.github.io",
      "branches": [
        {
          "branch": "main",
          "commits": [
            {
              "message": "Auto-generated blog posts and GitHub activity data [skip ci]",
              "url": "https://github.com/Blenux/Blenux.github.io/commit/066111fc62fcbd3235e69c54d6b2a38d383e4cf6",
              "date": "2026-08-31T03:54:59Z"
            },
            {
              "message": "Auto-generated blog posts and GitHub activity data [skip ci]",
              "url": "https://github.com/Blenux/Blenux.github.io/commit/8ecdfd59a6bca6fb5299363ab117290297981bfb",
              "date": "2026-08-30T20:37:42Z"
            },
            {
              "message": "Auto-generated blog posts and GitHub activity data [skip ci]",
              "url": "https://github.com/Blenux/Blenux.github.io/commit/ce4e1f439c85136399adecbc57def863085ed5d0",
              "date": "2026-08-30T16:07:07Z"
            },
            {
              "message": "Auto-generated blog posts and GitHub activity data [skip ci]",
              "url": "https://github.com/Blenux/Blenux.github.io/commit/ffc13e652a5253db415aac3916255a391394fa0a",
              "date": "2026-08-30T11:20:40Z"
            },
            {
              "message": "Auto-generated blog posts and GitHub activity data [skip ci]",
              "url": "https://github.com/Blenux/Blenux.github.io/commit/2e847dbf7bdb00070406375471a1173c90232277",
              "date": "2026-08-30T03:52:12Z"
            }
          ]
        }
      ]
    },
    {
      "name": "Blender-JBeam-Editor",
      "repoUrl": "https://github.com/Blenux/Blender-JBeam-Editor",
      "branches": [
        {
          "branch": "blenux-edits",
          "commits": [
            {
              "message": "little rewording",
              "url": "https://github.com/Blenux/Blender-JBeam-Editor/commit/7b32a88ba3ea0831ef948eaf94fd88b464a22e76",
              "date": "2023-09-27T16:04:44Z"
            },
            {
              "message": "Updated dev docs",
              "url": "https://github.com/Blenux/Blender-JBeam-Editor/commit/1b79cc20ba869fd6dc8d256194a44bc31a34d289",
              "date": "2023-09-27T16:04:02Z"
            },
            {
              "message": "updated version",
              "url": "https://github.com/Blenux/Blender-JBeam-Editor/commit/e9fc8899c83f8c6744d0b5595a9d8d26f8dca6c5",
              "date": "2023-09-27T15:18:10Z"
            },
            {
              "message": "Fixed node ids disappearing on loading a saved blend file. Moved \"draw_handle\" variable to top of file.",
              "url": "https://github.com/Blenux/Blender-JBeam-Editor/commit/8e7ee95ee91232a710fd167871f9eedd1f530a40",
              "date": "2023-09-26T03:13:16Z"
            },
            {
              "message": "Merge pull request #2 from Blenux/blenux-edits\n\nremoved dpi parameter from blf",
              "url": "https://github.com/Blenux/Blender-JBeam-Editor/commit/15502710960fdfca4b2b968bf1e5d39f1a9d3675",
              "date": "2023-09-24T03:11:29Z"
            }
          ]
        },
        {
          "branch": "main",
          "commits": [
            {
              "message": "fix TextIO import for Python 3.11 compatibility in ANTLR4 and Lua parser",
              "url": "https://github.com/Blenux/Blender-JBeam-Editor/commit/73d3350f3159c7d9f26ed9b9555dcd317ef57658",
              "date": "2026-06-19T07:16:38Z"
            },
            {
              "message": "Refactor: separate Blender UI from core JBeam logic\n\nRestructures the addon from a monolithic __init__.py into a clean\nlayered architecture:\n\n- Extract all Blender-specific code into blender/ subpackage:\n  - state.py, properties.py, drawing.py, handlers.py\n  - operators/ (core, mesh_edit, nodes)\n  - panels/ (main, properties_panel, tools)\n\n- Create registration.py for all Blender class registration\n- Flatten __init__.py to bl_info + thin register/unregister stubs\n- Fix domain layer imports (jbeam/*.py -> core.utils)\n\n- Remove Blender text_editor dependency from jbeam/io.py via\n  dependency injection (read_file_fn parameter)\n- Reorganize third-party code under parsers/ and vendor/\n\nNo functional changes — pure code organization.\"",
              "url": "https://github.com/Blenux/Blender-JBeam-Editor/commit/352aabab45d73b6aa11e7050b5dfaa30ee5e45b0",
              "date": "2026-06-19T07:06:33Z"
            },
            {
              "message": "updated CLA",
              "url": "https://github.com/Blenux/Blender-JBeam-Editor/commit/240af8826dfd006a9c630805b734f096bcfc3182",
              "date": "2024-08-09T16:37:28Z"
            },
            {
              "message": "updated docs to include new CLA",
              "url": "https://github.com/Blenux/Blender-JBeam-Editor/commit/d5f05fbc7cf0fb4404079c0ad66e9fbc0f8d9cb1",
              "date": "2024-08-08T15:39:31Z"
            },
            {
              "message": "Update README.md",
              "url": "https://github.com/Blenux/Blender-JBeam-Editor/commit/06ec8a001cba85b46dedcd0461d1d6f7ffb6f21c",
              "date": "2024-07-23T20:27:25Z"
            }
          ]
        },
        {
          "branch": "restructure",
          "commits": [
            {
              "message": "Refactor: separate Blender UI from core JBeam logic\n\nRestructures the addon from a monolithic __init__.py into a clean\nlayered architecture:\n\n- Extract all Blender-specific code into blender/ subpackage:\n  - state.py, properties.py, drawing.py, handlers.py\n  - operators/ (core, mesh_edit, nodes)\n  - panels/ (main, properties_panel, tools)\n\n- Create registration.py for all Blender class registration\n- Flatten __init__.py to bl_info + thin register/unregister stubs\n- Fix domain layer imports (jbeam/*.py -> core.utils)\n\n- Remove Blender text_editor dependency from jbeam/io.py via\n  dependency injection (read_file_fn parameter)\n- Reorganize third-party code under parsers/ and vendor/\n\nNo functional changes — pure code organization.\"",
              "url": "https://github.com/Blenux/Blender-JBeam-Editor/commit/352aabab45d73b6aa11e7050b5dfaa30ee5e45b0",
              "date": "2026-06-19T07:06:33Z"
            },
            {
              "message": "updated CLA",
              "url": "https://github.com/Blenux/Blender-JBeam-Editor/commit/240af8826dfd006a9c630805b734f096bcfc3182",
              "date": "2024-08-09T16:37:28Z"
            },
            {
              "message": "updated docs to include new CLA",
              "url": "https://github.com/Blenux/Blender-JBeam-Editor/commit/d5f05fbc7cf0fb4404079c0ad66e9fbc0f8d9cb1",
              "date": "2024-08-08T15:39:31Z"
            },
            {
              "message": "Update README.md",
              "url": "https://github.com/Blenux/Blender-JBeam-Editor/commit/06ec8a001cba85b46dedcd0461d1d6f7ffb6f21c",
              "date": "2024-07-23T20:27:25Z"
            },
            {
              "message": "Update README.md",
              "url": "https://github.com/Blenux/Blender-JBeam-Editor/commit/537311714b7e582f54e71d618814d7b4d5663dc3",
              "date": "2024-07-23T20:24:17Z"
            }
          ]
        }
      ]
    },
    {
      "name": "scripts",
      "repoUrl": "https://github.com/Blenux/scripts",
      "branches": [
        {
          "branch": "main",
          "commits": [
            {
              "message": "toggle_resolution script\n\ndisplayport 1440>1080p and vice versa.",
              "url": "https://github.com/Blenux/scripts/commit/4c519e8d83c905b237b0ea6b6bca54d4b0ebd233",
              "date": "2026-08-19T10:54:45Z"
            },
            {
              "message": "Initial commit",
              "url": "https://github.com/Blenux/scripts/commit/f9f1db4c83a35aff3030840505698f73345b2330",
              "date": "2025-12-29T00:24:37Z"
            }
          ]
        }
      ]
    },
    {
      "name": "io_beamng_dae_dev",
      "repoUrl": "https://github.com/Blenux/io_beamng_dae_dev",
      "branches": [
        {
          "branch": "main",
          "commits": [
            {
              "message": "Update/Add SPDX license identifier from GPL-2.0-or-later to GPL-3.0-or-later",
              "url": "https://github.com/Blenux/io_beamng_dae_dev/commit/6d4c9ebeac664ac3f62303cc04e22722b3c22a6e",
              "date": "2026-08-16T05:52:12Z"
            },
            {
              "message": "Add GPL-3.0 license file",
              "url": "https://github.com/Blenux/io_beamng_dae_dev/commit/490a36826db2864e17a5eeec9ae78272b6900a18",
              "date": "2026-08-16T05:32:24Z"
            },
            {
              "message": "remaining changes for 1.0.0 release",
              "url": "https://github.com/Blenux/io_beamng_dae_dev/commit/d36595785056a58b58c160c41510b03c3bc4cacd",
              "date": "2026-08-13T05:14:35Z"
            },
            {
              "message": "Remove cdae_native wheel files for Python 3.11 and 3.13",
              "url": "https://github.com/Blenux/io_beamng_dae_dev/commit/717c3c33d5bce498fbc99d820afc18f90403985a",
              "date": "2026-08-12T09:00:58Z"
            },
            {
              "message": "Initial commit",
              "url": "https://github.com/Blenux/io_beamng_dae_dev/commit/90afe022a9b74dbb6ec2ada725c95c42beeaf4f5",
              "date": "2026-08-12T07:19:53Z"
            }
          ]
        }
      ]
    }
  ],
  "contrib_repos": [
    {
      "name": "Bforartists",
      "full_name": "Bforartists/Bforartists",
      "html_url": "https://github.com/Bforartists/Bforartists",
      "description": "",
      "contrib": true
    }
  ],
  "contrib_detail": [
    {
      "name": "Bforartists",
      "repoUrl": "https://github.com/Bforartists/Bforartists",
      "branches": [
        {
          "branch": "main",
          "commits": [
            {
              "message": "6766-preferences---viewport---quality---improve-label-for-shadows-hardware-raytracing\n\n-- added indent",
              "url": "https://github.com/Bforartists/Bforartists/commit/176b9e583499dab376b6c741e4e9391e3c23fed4",
              "date": "2026-08-22T05:02:05Z"
            },
            {
              "message": "6766-preferences---viewport---quality---improve-label-for-shadows-hardware-raytracing\n\n| Before | After |\n|--------|--------|\n| <img width=\"672\" height=\"605\" alt=\"Image\" src=\"https://github.com/user-attachments/assets/419f72db-3b60-4bf6-a40f-37f290e038a1\" /> | <img width=\"797\" height=\"621\" alt=\"Image\" src=\"https://github.com/user-attachments/assets/b818c836-9622-4dc4-930f-c5a9ce8405c0\" /> |",
              "url": "https://github.com/Bforartists/Bforartists/commit/fb3af8a76dabfc9dd55538816a512cbb98c9f1c2",
              "date": "2026-08-19T23:17:54Z"
            },
            {
              "message": "6752-modular-child-addon---small-fix (#6753)\n\n-- missed this",
              "url": "https://github.com/Bforartists/Bforartists/commit/c5cac3b7e13d5bdcc884c88ce016b97615c98b62",
              "date": "2026-08-15T19:46:12Z"
            },
            {
              "message": "6729-splashscreen---make-it-bigger (#6748)\n\n-- Adjust the Splash Screen size 20%",
              "url": "https://github.com/Bforartists/Bforartists/commit/52b0959be7276f6235d54bea51d9e81a1c94b4e2",
              "date": "2026-08-13T14:51:48Z"
            },
            {
              "message": "6749-splashscreen---templaterecent-file-amount-change (#6750)\n\n-- adjusted splash_limit: 6 > 7\n-- adjusted found_recent: 5 > 6",
              "url": "https://github.com/Bforartists/Bforartists/commit/4b3259792a4008a8547f0cfb92ada02827335109",
              "date": "2026-08-13T14:51:24Z"
            },
            {
              "message": "6747-default-asset-library---functions-module-needs-improvement-policy-violation",
              "url": "https://github.com/Bforartists/Bforartists/commit/40aa587b7280c2da4e976bac8dbcaf2dad760e4f",
              "date": "2026-08-12T05:09:51Z"
            },
            {
              "message": "6732-properties-editor---world---open-node-editor-button-to-open-shad… (#6735)\n\nWorld Properties - Add Open Shader Editor operator button\n\nAdds a new \"Open Shader Editor\" button to the World Properties panel that opens a Shader Editor window configured for the active world's node tree. Implements WORLD_OT_open_node_editor operator following the same pattern as the existing material and texture node editor operators.",
              "url": "https://github.com/Bforartists/Bforartists/commit/65829a5acabcc8a52a5b9175badc51bdfed39774",
              "date": "2026-08-07T23:06:42Z"
            },
            {
              "message": "6731-properties-editor---materials---open-node-editor-button-only-wor… (#6734)\n\n-- Cycles Material Panel - Add Open Shader Editor operator button",
              "url": "https://github.com/Bforartists/Bforartists/commit/f14571f41862e5c6d82e07dc6bb8eedaa730750c",
              "date": "2026-08-07T23:06:33Z"
            },
            {
              "message": "3D View - Header - Overlay toggles - Add \"Lock Object Mode\" button (#6657)\n\n-- added lock object to the Align View Buttons addon",
              "url": "https://github.com/Bforartists/Bforartists/commit/611151108de2ad918a842fbc79f753d36bbe8ada",
              "date": "2026-06-22T15:11:33Z"
            },
            {
              "message": "Sequencer - Color Strip - Add Width and Height to sidebar (#6647)\n\n-- Replaced the manual duplicated codebase of the strip classes (which can get outdated), and instead just directly import the Strip Properties contents.",
              "url": "https://github.com/Bforartists/Bforartists/commit/622107c6d2f5764bf76b4dc95a1e1c3d1e8e7018",
              "date": "2026-06-15T22:45:34Z"
            }
          ]
        }
      ]
    }
  ]
};
